[package]
name = "pachou-backend"
version = "0.1.0"
authors = ["Sam Samai <sam@studio2pi.com.au>"]
edition = "2021"
publish = false

[workspace]
members = [".", "api", "core", "entity", "migration", "crud_macro"]

[dependencies]
pachou-backend-api = { path = "api" }
